### ISSUE TITLE
Project Management SRS: Methods/Tools

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#20]

**Comment by CaseeNewton** [comment]
The methodologies we are using are Agile, Scrum and Kanban. 

In our use of GitHub we can see a layout of tasks that are in our inbox, in progress, in review, and completed. This method is mainly using the Kanban method to see and move in real time what is needing to be done vs is done. 

We are using Scrum methodology in our meetings. We have now started to meet twice a week with our team for scrum meetings (we are not able to meet daily but do communicate via Practera and Teams more often). Our group leader is our scrum master. We chose to use this method because our project is broken into week to two-week intervals that we can use as our sprints to track our progress better.

Agile methodology is also being used in our group project. We are using it as a method to self-organize because we are unable to meet in a group setting daily. It has been helpful to the project for everyone to gather their project planning and deliver it together to create the most effective path and tools to use for our Parking Lot Project.
